Remove unnecessary and incorrect check on maintainers.
kubeapps/kubeapps pull request #3187
Opened 2021-07-23 05:52 UTC by absoludity

### Description of the change

Dimitri pointed out that the check on these seemed odd (why check ChartVersions at all?).

There's actually no need for checking whether chart.Maintainers is nil or not since nil is the zero value for arrays, a range of it results in nothing to iterate.

The existing tests in TestIsValidChart demo this already (examples with nil maintainers).

I'm not yet sure about sharing code between plugins, so for now haven't dealt with that (but more than happy if you want to have a go Dimitri).

### Benefits

Removes confusing code :)

### Possible drawbacks

None.

2021-07-23 06:04 UTC, dlaloue-vmware approved these changes
looks good

2021-07-23 06:25 UTC, gfichtenholt reviewed
no need to fix flux plug in. I re-organized the code and will fix it myself. Thanks

2021-07-23 11:05 UTC, antgamdia commented
> There's actually no need for checking whether chart.Maintainers is nil or not since nil is the zero value for arrays, a range of it results in nothing to iterate

Ooops, I read the (offline) conversation and I agree, it's odd how go manages `nil` references. I wrote that check (my bad!) I still have to assimilate and get used to :p  
Thanks for the PR +1

2021-07-23 11:40 UTC, gfichtenholt commented
Well, Michael had explained that you have to change your way of looking at this. Go is NOT an object-oriented language. Technically, we are not calling methods on objects. It's this subtle difference between objects and function receivers, which isn't covered that well in the go intro or FAQs, I looked. This is where experience plays a big part. Not that I agree with these decisions, they definitely look odd for a guy coming from C/C++/Java background. Oh well. It is what it is, as they say here.

2021-07-28 04:30 UTC, gfichtenholt requested changes
yeah, fluxv2 files are way of out date. Please exclude them from this PR

2021-07-28 05:04 UTC, absoludity commented
> yeah, fluxv2 files are way of out date. Please exclude them from this PR

I did already? You'll see above your message that I'd updated a second time after I realised the same thing :)

2021-07-29 00:20 UTC, absoludity commented
> > yeah, fluxv2 files are way of out date. Please exclude them from this PR
> 
> I did already? You'll see above your message that I'd updated a second time after I realised the same thing :)

Ping @gfichtenholt  ^^ I'd already removed all changes to the flux2 plugin before you finished your comment as you can see above (though you would not have known that at the time you commented, but it would be great to unblock the PR).

2021-07-29 04:51 UTC, gfichtenholt commented
> > > yeah, fluxv2 files are way of out date. Please exclude them from this PR
> > 
> > 
> > I did already? You'll see above your message that I'd updated a second time after I realised the same thing :)
> 
> Ping @gfichtenholt ^^ I'd already removed all changes to the flux2 plugin before you finished your comment as you can see above (though you would not have known that at the time you commented, but it would be great to unblock the PR).

yeah, ok, good. Sorry didn't realize you were waiting for me to respond

2021-07-29 04:52 UTC, gfichtenholt approved these changes

2021-07-29 04:53 UTC, merged