fix(chart): Skip README when it cannot be found
kubeapps/kubeapps pull request #3227
Opened 2021-07-30 21:18 UTC by aanthonyrizzo

Signed-off-by: Anthony Rizzo <36711320+aanthonyrizzo@users.noreply.github.com>

### Description of the change

This PR adds a logical statement to redirect and not render the `<ChartReadme />` when there is a README error. Since I only want to redirect when the file is not found, I check the error as such `.includes("not found")`. I cant see why having this as the default behavior but this can easily be controlled w/ a config variable if we wanted.

### Benefits

This change will circumvent the no README error and direct the user to the deployment form

### Possible drawbacks

I don't see any but I could be wrong

### Applicable issues

Fixes #3226

2021-09-02 03:04 UTC, absoludity commented
See comment at https://github.com/kubeapps/kubeapps/issues/3226#issuecomment-899878636 for more info about this PR.

2021-09-08 11:59 UTC, antgamdia requested changes
_(just updating the status of the PR according to what it was said)_

2021-09-23 14:39 UTC, aanthonyrizzo commented
Sorry guys I haven't had time to work on this recently. I will get back on this next week.

2021-09-24 14:55 UTC, ppbaena commented
Thank you @aanthonyrizzo for the info! 
We have configured this bot mainly to stale discontinued issues, but also as a kindly reminder for situations like you mention. Next week more!

2021-09-28 19:34 UTC, antgamdia reviewed
Let us know when it is ready for review so that we can pull and test the changes. And, as usual, thanks a lot for your contributions!

2021-09-28 19:34 UTC, antgamdia commented on dashboard/src/containers/RoutesContainer/Routes.tsx
> +  "/c/:cluster/ns/:namespace/apps/new/:repo/:pluginName/:pluginVersion/:id/versions/":
Mmmm, `latest` would imply a single version... but you are still able to select multiple ones from the dropdown... so, perhaps `versions` fits better here, no? No strong opinion anyway,

2021-09-28 19:34 UTC, antgamdia commented on dashboard/src/components/DeploymentForm/DeploymentForm.tsx
> +    console.log(e.target.value);
leftover :P

2021-09-28 20:16 UTC, aanthonyrizzo commented on dashboard/src/components/DeploymentForm/DeploymentForm.tsx
> +    console.log(e.target.value);
🤦‍♂️

2021-10-17 14:05 UTC, aanthonyrizzo commented
> Sorry for the delay on this one Anthony. If you can rebase with current master, I'll try to get it reviewed and landed ASAP, early in our next cycle.

Hi I also want to apologize, crazy week, I should be able to finish this early next week (Monday has the potential to be very busy so it might be Tuesday)

2021-11-05 18:24 UTC, closed without merging

2021-11-10 16:23 UTC, antgamdia commented
Oops, it seems our bot closed it. @aanthonyrizzo, I guess you didn't have a chance to get back to it, don't worry; do you want us to cherry-pick your changes in another PR?

2021-11-10 20:55 UTC, aanthonyrizzo commented
> Oops, it seems our bot closed it. @aanthonyrizzo, I guess you didn't have a chance to get back to it, don't worry; do you want us to cherry-pick your changes in another PR?

Yeah I was going to open another PR since this got so far behind with all of the route changes you guys made when changing the chart => package nomenclature but I've been so swamped w/ other work I just havent had the time.  If you could that would be super awesome :)

2021-11-10 21:38 UTC, antgamdia commented
Great, awesome! I just didn't want to jump in w/o letting you know first. No problem, sometimes we all got overwhelmed with tons of things on our plate hehe.
Thanks for your words, glad you liked it!!   :blush: